### ISSUE TITLE
Making the map fill out the page

### ISSUE THREAD

**Issue by siyuanji1** [info442-su23/d-team#95]
After I clicked the "Explore Map" button on the home page, I was brought to a page containing the map. However, I noticed that it only displayed the map in the left corner of the screen, which seemed awkward and limited in its presentation. It would be more visually appealing and functional if the map could fill the entire page or at least half of it. This adjustment would make navigation easier and provide a better user experience.

**Comment by Zuoooooo** [comment]
<img width="1440" alt="Screen Shot 2023-08-08 at 5 32 07 PM" src="https://github.com/info442-su23/d-team/assets/114701960/777d7eb5-5bd2-48b8-b23a-de3f72fc8af4">

**Comment by ericagordy** [comment]
<img width="657" alt="Screenshot 2023-08-08 at 5 39 47 PM" src="https://github.com/info442-su23/d-team/assets/66372667/4a25c8e2-e80c-49ae-a43d-6ef8192e8b6d">
In order to view any of the sites to volunteer I must be signed in. I do not know if this was a functionality choice or an over site. What if I want to see volunteer locations before deciding to sign up?

**Comment by FastFusion5** [comment]
We are planning to add a filter function beside the map, hence the blank space on the right. We are working to implement that.

**Comment by elisabeth-h7** [comment]
filter function was added and formatting for map was updated
